const SUPABASE_URL = 'https://sastokjxydnlujfvvagr.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = 'sb_publishable_3oph1JvGDTPaDlP1DRebjw_XVE4gQOi';
const ADMIN_EMAIL = 'cristian85barrionuevo@gmail.com';
const WHATSAPP = '5492634587402';
const sb = window.supabase.createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
let products=[], cart=JSON.parse(localStorage.getItem('limarCart')||'[]'), active='Todos', editId=null, adminUnlocked=false, loading=true;
const fallbackProducts=typeof initialProducts!=='undefined'?initialProducts.map(normalize):[];
const money=n=>n?new Intl.NumberFormat('es-AR',{style:'currency',currency:'ARS',maximumFractionDigits:0}).format(n):'Consultar';
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const saveCart=()=>localStorage.setItem('limarCart',JSON.stringify(cart));
function normalize(p){return {...p,id:String(p.id),price:Number(p.price||0),group:p.description||p.category||'',image:p.image_url||''};}
async function loadProducts(){loading=true;render();products=fallbackProducts.slice();loading=false;render();}
function showStatus(text,error=false){const el=document.getElementById('status');if(!el)return;el.textContent=text;el.style.display=text?'block':'none';el.style.background=error?'#fff0f0':'#e5f7ef';el.style.color=error?'#9b3030':'#176d4e';}
function categories(){return ['Todos',...new Set(products.map(p=>p.category).filter(Boolean))]}
function renderFilters(){document.getElementById('filters').innerHTML=categories().map(c=>`<button class="filter ${c===active?'active':''}" onclick="active=${JSON.stringify(c)};render()">${esc(c)}</button>`).join('')}
function render(){renderFilters();const q=(document.getElementById('search')?.value||'').toLowerCase();const list=products.filter(p=>(active==='Todos'||p.category===active)&&`${p.name} ${p.group} ${p.category}`.toLowerCase().includes(q));document.getElementById('summary').textContent=loading?'Cargando catálogo…':`${list.length} productos · Tocá “Agregar” para preparar tu pedido`;document.getElementById('grid').innerHTML=loading?'<div class="empty">Cargando productos y precios…</div>':list.map(p=>`<article class="card">${p.image?`<img class="product-image" src="${esc(p.image)}" alt="${esc(p.name)}">`:'<div class="product-image empty-image">L</div>'}<span class="cat">${esc(p.category)}</span><h3>${esc(p.name)}</h3><span class="group">${esc(p.group)}</span><span class="price">${money(p.price)}</span><button class="add" onclick="add('${esc(p.id)}')">Agregar al carrito</button></article>`).join('')||'<div class="empty">No encontramos ese producto. Probá con otra búsqueda.</div>';renderCart();}
function add(id){const x=cart.find(i=>i.id===id);x?x.qty++:cart.push({id,qty:1});saveCart();renderCart();openCart()}
function change(id,d){const x=cart.find(i=>i.id===id);if(!x)return;x.qty+=d;if(x.qty<1)cart=cart.filter(i=>i.id!==id);saveCart();renderCart()}
function renderCart(){document.getElementById('count').textContent=cart.reduce((a,i)=>a+i.qty,0);const items=cart.map(i=>{const p=products.find(x=>x.id===i.id);return p?`<div class="cart-line"><div><b>${esc(p.name)}</b><small>${esc(p.group)} · ${money(p.price)}</small><button class="remove" onclick="change('${esc(p.id)}',-99)">Quitar</button></div><div class="qty"><button onclick="change('${esc(p.id)}',-1)">−</button><b>${i.qty}</b><button onclick="change('${esc(p.id)}',1)">+</button></div></div>`:''}).join('');document.getElementById('cartItems').innerHTML=items||'<div class="empty">Tu carrito está vacío.<br>Agregá productos para comenzar.</div>';const total=cart.reduce((a,i)=>{const p=products.find(x=>x.id===i.id);return a+(p?p.price*i.qty:0)},0);document.getElementById('cartFooter').innerHTML=cart.length?`<div class="cart-total"><span>Total</span><span>${money(total)}</span></div><button class="primary" style="width:100%" onclick="openCheckout()">Continuar con mis datos</button>`:''}
function openCart(){document.getElementById('drawer').classList.add('open')}function closeCart(){document.getElementById('drawer').classList.remove('open')}function openCheckout(){if(!cart.length)return;closeCart();document.getElementById('checkout').classList.add('open')}function closeCheckout(){document.getElementById('checkout').classList.remove('open')}
async function sendOrder(e){e.preventDefault();const name=document.getElementById('customerName').value.trim(),phone=document.getElementById('customerPhone').value.trim(),address=document.getElementById('customerAddress').value.trim(),notes=document.getElementById('customerNotes').value.trim();const rows=cart.map(i=>({i,p:products.find(x=>x.id===i.id)})).filter(x=>x.p);const total=rows.reduce((a,x)=>a+x.p.price*x.i.qty,0);const lines=rows.map(x=>`• ${x.i.qty} x ${x.p.name} — ${money(x.p.price*x.i.qty)}`).join('\n');const msg=`Hola Fragancias LiMar, quiero hacer este pedido:\n\n${lines}\n\nTotal: ${money(total)}\nPago: contra entrega\n\nDatos del cliente:\nNombre: ${name}\nTeléfono: ${phone}\nDirección: ${address}${notes?'\nObservaciones: '+notes:''}`;const button=e.target.querySelector('button[type="submit"]');if(button){button.disabled=true;button.textContent='Preparando pedido…'};try{await sb.rpc('create_order_with_items',{order_data:{customer_name:name,customer_phone:phone,delivery_address:address,notes,total},items:rows.map(x=>({product_id:x.p.id,product_name:x.p.name,unit_price:x.p.price,quantity:x.i.qty}))})}catch(err){console.warn('No se pudo guardar el pedido, se continúa por WhatsApp',err)}window.open(`https://wa.me/${WHATSAPP}?text=${encodeURIComponent(msg)}`,'_blank');cart=[];saveCart();closeCheckout();renderCart();e.target.reset();if(button){button.disabled=false;button.textContent='Enviar pedido por WhatsApp'}}
function openAdmin(){document.getElementById('adminLogin').style.display='block';document.getElementById('adminPanel').style.display='none';document.getElementById('adminEmail').value=ADMIN_EMAIL;document.getElementById('adminPassword').value='';document.getElementById('loginError').textContent='';document.getElementById('admin').classList.add('open');setTimeout(()=>document.getElementById('adminPassword').focus(),50)}
async function unlockAdmin(){const email=document.getElementById('adminEmail').value.trim(),password=document.getElementById('adminPassword').value,button=document.querySelector('#adminLogin .primary');if(button){button.disabled=true;button.textContent='Ingresando…'}const {data,error}=await sb.auth.signInWithPassword({email,password});if(error||!data.session||email.toLowerCase()!==ADMIN_EMAIL){document.getElementById('loginError').textContent='Correo o contraseña incorrectos.';if(button){button.disabled=false;button.textContent='Entrar al panel'};return}adminUnlocked=true;document.getElementById('adminLogin').style.display='none';document.getElementById('adminPanel').style.display='block';clearForm();renderAdmin();if(button){button.disabled=false;button.textContent='Entrar al panel'}}
async function closeAdmin(){document.getElementById('admin').classList.remove('open');adminUnlocked=false;await sb.auth.signOut()}
function clearForm(){['pName','pCat','pGroup','pPrice','pImage'].forEach(id=>{const el=document.getElementById(id);if(el)el.value=''});document.getElementById('imagePreview').innerHTML='';editId=null}
function loadImage(){document.getElementById('imagePreview').innerHTML='<small style="color:#76616a">Las imágenes se administran desde el catálogo principal.</small>'}
function removeImage(){document.getElementById('pImage').value='';document.getElementById('imagePreview').innerHTML=''}
async function saveProduct(){if(!adminUnlocked)return;const name=document.getElementById('pName').value.trim(),category=document.getElementById('pCat').value.trim()||'Otros Productos',description=document.getElementById('pGroup').value.trim()||category,price=Number(document.getElementById('pPrice').value)||0;if(!name)return alert('Completá el nombre del producto');const button=document.querySelector('#adminPanel .admin-form .primary');if(button){button.disabled=true;button.textContent='Guardando…'}try{let result;if(editId)result=await sb.from('products').update({name,category,description,price,active:true}).eq('id',editId);else result=await sb.from('products').insert({name,category,description,price,active:true});if(result.error)throw result.error;await loadProducts();clearForm();renderAdmin();showStatus('Catálogo actualizado.')}catch(err){console.error(err);alert('No se pudo guardar el producto.')}if(button){button.disabled=false;button.textContent='Guardar producto'}}
function editProduct(id){const p=products.find(x=>x.id===id);if(!p)return;editId=id;document.getElementById('pName').value=p.name;document.getElementById('pCat').value=p.category;document.getElementById('pGroup').value=p.group;document.getElementById('pPrice').value=p.price}
async function deleteProduct(id){if(!adminUnlocked||!confirm('¿Eliminar este producto del catálogo compartido?'))return;const {error}=await sb.from('products').update({active:false}).eq('id',id);if(error){alert('No se pudo eliminar el producto.');return}cart=cart.filter(i=>i.id!==id);saveCart();await loadProducts();renderAdmin()}
function renderAdmin(){document.getElementById('adminList').innerHTML=products.map(p=>`<div class="admin-row"><span>${esc(p.name)}<br><small>${esc(p.category)} · ${money(p.price)}</small></span><button onclick="editProduct('${esc(p.id)}')">Editar</button><button class="danger" onclick="deleteProduct('${esc(p.id)}')">Quitar</button></div>`).join('')}
loadProducts();
